version: '2'
services:
  backend:
    image: ddevilbb/test-reqres-backend:latest
    env_file:
      - .env.dev
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 4000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - postgres
    networks:
      default:
        ipv4_address: 10.201.0.2

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${POSTGRES_DB},${POSTGRES_DB_TEST}
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data
      - ./create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    networks:
      default:
        ipv4_address: 10.201.0.3
    ports:
      - 5432:5432

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.201.0.0/16
          gateway: 10.201.0.1
